### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jason9693** [jason9693/MusicTransformer-tensorflow2.0#4]
- [ ] Resource Reduced Model
- [ ] Distribute Strategy
- [ ] README for Korean
- [ ] preprocessing with method1
